CREATE DATABASE IF NOT EXISTS userdb;
CREATE DATABASE IF NOT EXISTS salondb;
CREATE DATABASE IF NOT EXISTS categorydb;
CREATE DATABASE IF NOT EXISTS offeringdb;
CREATE DATABASE IF NOT EXISTS bookingdb;
CREATE DATABASE IF NOT EXISTS paymentdb;